config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :lists, only: [:index, :show, :create] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  include PgSearch::Model
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  pg_search_scope :global_search,
                  against: [:name],
                  using: {
                    tsearch: { prefix: true },
                  }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      @movies = Movie.all
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
    @list = List.new

    if params[:list].present? && params[:list][:query].present?
      @lists = List.global_search(params[:list][:query])
    end
  end

  def show
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List was successfully created."
      redirect_to @list
    else
      render :index, status: :unprocessable_entity # Re-renders the new form with errors
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7WatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootswatch@5.3.6/dist/brite/bootstrap.min.css" %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="my-3">
    <div class="d-flex w-100 gap-3">
      <p class="d-inline-flex gap-1">
        <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Make a list
        </button>
      </p>
      <div class="col p-0">
        <div class="container-fluid">
          <%= simple_form_for :list, url: lists_path, method: :get, html: { class: "d-flex" } do |f| %>
            <%= f.input :query,
              as: :string,
              input_html: { class: "form-control me-2", placeholder: "Type a keyword", value: params[:query] },
              wrapper: false,
              label: false,
              placeholder: "Type a keyword"
            %>
            <%= f.button :submit, "Search", class: "btn btn-primary", name: "" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="collapse" id="collapseExample">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, label: "Make a List", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <%= link_to list, class: "col-sm-12 col-md-4 col-lg-2 mb-3" do %>
        <div class="card">
          <%= render "shared/carousel", movies: list.movies, list: list %>
          <div class="card-body">
            <p class="card-title">
              <%= list.name.capitalize %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between">
    <h1><%=  @list.name %></h1>
    <p class="d-inline-flex gap-1">
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa-solid fa-plus"></i>
      </button>
    </p>
  </div>
  <div class="mb-3">
    <div class="collapse" id="collapseExample">
      <%= simple_form_for [ @list, @bookmark ] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-sm-12 col-md-6 col-lg-4 mb-3">
        <div class="card">
          <div class="card-body">
            <%= image_tag "#{bookmark.movie.poster_url}", class: "card-img-top", alt: "#{bookmark.movie.title} poster" %>
            <div class="d-flex justify-content-between mt-2">
              <h5 class="card-title fw-bold text-truncate"><%= bookmark.movie.title %></h5>
              <div class="d-flex gap-2">
                <p class="card-text text-nowrap">
                  <%= bookmark.movie.rating.round(1) %>
                  <i class="fa-solid fa-star text-warning"></i>
                </p>
              </div>
            </div>
            <p class="card-text overflow-scroll" style="height: 100px"><%= bookmark.movie.overview %></p>
            <p class="card-title fw-bold">Comments</p>
            <p class="overflow-scroll" style="height: 100px"><%= bookmark.comment %></p>
            <%= link_to bookmark, class: "btn btn-danger float-end", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id=<%= "#{list.name}#{list.id} carousel" %> class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% movies.each_with_index do |movie, index| %>
      <div class="carousel-item <%= "active" if index == 0%>" data-bs-interval="10000">
        <img src="<%= movie.poster_url %>" class="d-block w-100" alt="<%= movie.title %>">
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg bg-primary" style="height: 4rem;">
  <div class="container">
    <div class="row justify-content-between align-items-center w-100">
      <div class="col p-0">
        <div class="container-fluid">
          <%= link_to '🎬 Movie List', root_path %>
        </div>
      </div>
    </div>
  </div>
</nav>